name: Build TensorRT-LLM

on:
  push:
    branches:
      - 'main'
      - 's3-cache'
    tags:
      - 'v*'
  pull_request:
    paths:
      - "backends/**"
      - "server/**"
      - "proto/**"
      - "router/**"
      - "launcher/**"
      - "Cargo.lock"
      - "rust-toolchain.toml"
    branches:
      - "main"

permissions:
  contents: read # Required to check out repository.
  id-token: write # Required to authenticate via OIDC.
  
jobs:
  call-setup-aws-s3-cache:
    uses: ./.github/workflows/s3-cache.yaml  # TODO: Change @s3-cache to @main when merged
    with:
      runner-group: aws-highmemory-32-plus-priv
    secrets: inherit

  build:
    runs-on:
      group: aws-highmemory-32-plus-priv
    needs: call-setup-aws-s3-cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Install sccache"
        run: cargo install sscache




