name: Build TensorRT-LLM

on:
  push:
    branches:
      - 'main'
      - 'trtllm/ci'
    tags:
      - 'v*'
  pull_request:
    paths:
      - "backends/trtllm"
      - "server/**"
      - "proto/**"
      - "router/**"
      - "launcher/**"
      - "Cargo.lock"
      - "rust-toolchain.toml"
    branches:
      - "main"

permissions:
  contents: read # Required to check out repository.
  id-token: write # Required to authenticate via OIDC.

jobs:
  build:
    runs-on:
      group: aws-highmemory-32-plus-priv
    steps:
      - uses: actions/checkout@v4

      - name: Extract TensorRT-LLM version
        run: |
          echo "TENSORT_LLM_VERSION=$(grep -oP '([a-z,0-9]{40})' backends/trtllm/cmake/trtllm.cmake)" >> $GITHUB_ENV

      - name: Setup Github Actions Caching Layer
        uses: actions/cache@v4
        with:
          path: .sccache
          key: trtllm_${{ env.TENSORRT_LLM_VERSION }}_linux-gnu-x86_64-gcc14

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-config: /tmp/buildkitd.toml

      - name: Build and push Docker image
        id: build-and-push
        env:
          LABEL: "trtllm"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_trtllm
          target: runtime
          push: false
          load: true
          platforms: 'linux/amd64'
          build-args: |
            SCCACHE_LOG=debug
            SCCACHE_NO_DAEMON=1
            BUILD_TYPE=dev
            SCCACHE_GHA_ENABLED=true
          secrets:
            gha_cache_url=${{ACTIONS_CACHE_URL}}
            gha_cache_token=${{ACTIONS_CACHE_TOKEN}}
          cache-from: type=s3,region=us-east-1,bucket=ci-docker-buildx-cache,name=text-generation-inference-cache-${{ env.LABEL }},mode=min,access_key_id=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_ACCESS_KEY_ID }},secret_access_key=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_SECRET_ACCESS_KEY }},mode=min
          cache-to: type=s3,region=us-east-1,bucket=ci-docker-buildx-cache,name=text-generation-inference-cache-${{ env.LABEL }},mode=min,access_key_id=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_ACCESS_KEY_ID }},secret_access_key=${{ secrets.S3_CI_DOCKER_BUILDX_CACHE_SECRET_ACCESS_KEY }},mode=min







